mass_contact.category.*:
  type: config_entity
  label: 'Mass contact category config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    recipients:
      type: sequence
      label: 'Recipient groupings'
      sequence:
        type: mapping
        mapping:
          grouping:
            type: string
            label: 'GroupingInterface plugin ID'
          categories:
            type: sequence
            label: 'Categories'
            sequence:
              type: string
              label: 'Category ID'
          conjunction:
            type: string
            label: 'Conjunction for finding recipients'
    selected:
      type: boolean
      label: 'Selected by default'
