mass_contact.settings:
  type: config_object
  label: 'Mass Contact ettings'
  mapping:
    form_information:
      type: string
      label: 'Additional form help text'
    recipient_limit:
      type: integer
      label: 'Recipient limit'
    send_with_cron:
      type: boolean
      label: 'Send with cron/job queue'
    optout_enabled:
      type: string
      label: 'Allow users to opt-out of emails'
    create_archive_copy:
      type: boolean
      label: 'Create and archive copy of the email'
    hourly_threshold:
      type: integer
    character_set:
      type: string
    default_sender_name:
      type: string
    default_sender_email:
      type: string
    category_display:
      type: string
    include_from_name:
      type: boolean
    include_to_name:
      type: boolean
    use_bcc:
      type: boolean
    category_override:
      type: boolean
    number_of_attachments:
      type: integer
    attachment_location:
      type: string
    message_format:
      type: string
      label: 'Message format to use'
    message_prefix:
      type: text_format
      label: 'Text to prepend to all messages'
    message_suffix:
      type: text_format
      label: 'Text to append to all messages'
    wait_time:
      type: integer
